questions = [
    "If you could have any superpower, what would it be and why?",
    "What's the most adventurous thing you've ever done?",
    "If you could travel anywhere right now, where would you go?",
    "What's your favorite childhood memory?",
    "If you could have dinner with any historical figure, who would it be?",
    "What's the most unusual food you've ever tried?",
    "If you could instantly master any skill, what would it be?",
    "What's your dream job that doesn't exist yet?",
    "If you could trade lives with anyone for a day, who would it be?",
    "What's the best piece of advice you've ever received?",
    "If you could bring back any extinct animal, which one would you choose?",
    "What's your favorite way to relax after a long day?",
    "If you could instantly learn any language, which would you choose?",
    "What's the most interesting place you've ever visited?",
    "If you could have any animal as a pet (real or mythical), what would it be?",

    "What’s the dumbest thing you believed as a kid?",
    "If you had a theme song that played every time you entered a room, what would it be?",
    "Would you rather fight 100 duck-sized horses or 1 horse-sized duck?",
    "What’s the weirdest talent you have?",
    "If your life was a movie, what would the title be?",
    "What’s a smell that instantly makes you nostalgic?",
    "If aliens came to Earth and asked you to represent humanity, what’s the first thing you’d say?",
    "If you could swap bodies with an animal for a day, which animal would you pick?",
    "What conspiracy theory do you secretly kinda believe?",
    "What’s your guilty pleasure TV show or song?",
    "If you could live inside one video game world, which would it be?",
    "What’s your zombie apocalypse survival plan?",
    "If you had to eat only one food for the rest of your life, what would it be?",
    "Which fictional character would be your best friend in real life?",
    "Would you rather always be 10 minutes late or 20 minutes early?",
    "What’s the most embarrassing fashion trend you’ve ever rocked?",
    "If you could turn invisible at will, what’s the first thing you’d do?",
    "Which movie do you quote the most?",
    "If your pet could suddenly talk, what’s the first thing they’d say about you?",
    "What’s the most useless skill you have?",
    "What’s the weirdest place you’ve ever slept?",
    "If you could teleport anywhere instantly, where would you go first?",
    "Beach or mountains?",
    "If you could live in any country for a year, which one would you choose?",
    "What’s the coolest landmark you’ve ever visited?",
    "Which city would you never want to visit again?",
    "Have you ever gotten lost on purpose?",
    "What’s the strangest custom you’ve experienced in another culture?",
    "If you could design your dream vacation, what would it include?",
    "What’s the scariest travel experience you’ve had?",
    "Do you think humans are naturally good or evil?",
    "What do you think happens after we die?",
    "Would you rather know how the world ends or when?",
    "Do you think time travel will ever be possible?",
    "What’s something you’ll never understand about people?",
    "If you could live forever, would you?",
    "Is free will real or just an illusion?",
    "What’s scarier: deep space or deep ocean?",
    "If you could ask your future self one question, what would it be?",
    "Would you sacrifice one person to save a hundred?",
    "Do you believe in fate or randomness?",
    "What’s your biggest fear you’ll never admit in public?",
    "If you could erase one memory, would you?",
    "Would you rather know the truth even if it hurts, or stay blissfully ignorant?",
    "If you met God, what’s the first question you’d ask?",
    "What’s the meaning of happiness for you?",
    "Do you think dreams have hidden meanings?",
    "What’s your definition of success?",
    "Would you take a pill that makes you 10% smarter but 10% less happy?",
    "Is love more about passion or stability?",
    "What’s more important: truth or kindness?",
    "Would you rather explore space or the bottom of the ocean?",
    "What moment in history would you like to witness firsthand?",
    "Do you think AI will ever become conscious?",
    "What’s the greatest invention of all time?",
    "If you had one do-over in life, what would you change?",
    "Would you rather be remembered or forgotten?",
    "Is there such a thing as destiny?",
    "Do you think humanity will survive another 1000 years?",
    "What’s one question you never want answered?",
    "Would you upload your mind into a computer if it meant living forever?",
    "If you could remove one emotion from humanity, which would it be?",
    "Do you think humans are the only intelligent life in the universe?",
    "What’s one law you’d make mandatory for the whole world?",
    "If you could live in any time period, past or future, where would you go?",
    "Would you rather have more time or more money?",
    "What’s your most irrational fear?",
    "Do you believe in karma?",
    "Would you rather always know when someone is lying, or be able to lie without anyone knowing?",
    "What’s something you’ve done that felt small but changed your life?",
    "What’s one thing you think people should experience at least once?",
    "If you could delete one word from existence, what would it be?",
    "Do you think the world is getting better or worse?",
    "Would you rather lose all your memories or never be able to make new ones?",
    "What’s your happiest accident in life?",
    "Would you rather see your future or change your past?",
    "What do you think is humanity’s biggest weakness?",
    "Would you rather know all the secrets of the universe or every detail of your own future?",
    "What’s the hardest decision you’ve ever made?",
    "Do you think people are born with a purpose?",
    "Would you rather save your younger self from mistakes or watch your future self succeed?",
    "If your life had a soundtrack, what three songs would be on it?",
    "Do you think money really buys happiness?",
    "Would you rather be feared or loved?",
    "What do you think is the biggest lie society tells us?",
    "Would you rather never feel pain again or never feel fear again?",
    "Do you think happiness is a choice?",
    "What would you write in a letter to your 10-years-older self?",
    "What do you think will be the next big human breakthrough?",
    "Would you rather live in reality or a perfect simulation?",
    "What do you think is the rarest emotion?",
    "Do you believe people can truly change?",
    "Would you rather erase all wars from history or all diseases?",
    "Do you think technology is making us smarter or dumber?",
    "If you could witness your own funeral, would you?",
    "What’s one question you think everyone should ask themselves daily?",
    "Would you rather know everyone’s thoughts or have no one ever know yours?",
    "Do you think peace is actually possible?",
    "If the world ended tomorrow, what would you regret the most?",
    "Would you rather lose your sense of taste or your sense of touch?",
    "Do you think morality is objective or subjective?",
    "What do you think is humanity’s greatest strength?",
    "If you could know the answer to any mystery, which one would you pick?",
    "Would you rather travel to the past and meet your ancestors, or the future and meet your descendants?"
]
